# Generated by Django 2.0 on 2019-07-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(2, 'Student'), (1, 'Super Admin'), (3, 'Teacher')], null=True),
        ),
    ]
